blank_issues_enabled: false

contact_links:
  - name: Documentation
    url: https://github.com/pushpasta/simple-honeypot-cf7
    about: Read the documentation and FAQ first.

  - name: Support & Questions
    url: https://github.com/pushpasta/simple-honeypot-cf7/discussions
    about: Ask questions and get community help.
